services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443" 
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://tiago.42.fr:443"]
      interval: 30s  # Check every 30 seconds
      timeout: 10s   # Timeout after 10 seconds
      retries: 3     # Retry 3 times before marking unhealthy
      start_period: 10s  # Allow 10 seconds for startup before checks begin
    # init: true
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress
      
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    networks:
      - inception
    env_file:
      - .env
    # environment:
    #   DB_PASSWORD_FILE: /run/secrets/db_password
    #   MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    #   MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mariadb-data:/var/lib/mysql/
    # ports:
    #   - "3306:3306"
    # init: true
    restart: on-failure
    # secrets:
    #   - db_password
    #   - mysql_password
    #   - mysql_root_password
      
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    networks:
      - inception
    env_file:
      - .env
    # environment:
    #   DB_PASSWORD_FILE: /run/secrets/db_password
    #   WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    #   WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
    volumes:
      - wordpress-data:/var/www/html/
    # ports:
      # - "9000:9000"
    # init: true
    restart: on-failure
    depends_on:
      - mariadb
    # secrets:
    #   - db_password
    #   - wp_user_password
    #   - wp_admin_password

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress-data
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

# secrets:
#   db_password:
#     file: ../secrets/DB_PASSWORD.txt
#   mysql_password:
#     file: ../secrets/MYSQL_PASSWORD.txt
#   mysql_root_password:
#     file: ../secrets/MYSQL_ROOT_PASSWORD.txt
#   wp_admin_password:
#     file: ../secrets/WP_ADMIN_PASSWORD.txt
#   wp_user_password:
#     file: ../secrets/WP_USER_PASSWORD.txt
