services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443"
    init: true
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress
      
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_DB_PASS: /run/secrets/wp_db_pass
      DB_ROOT_PASS: /run/secrets/db_root_pass
    volumes:
      - mariadb-data:/var/lib/mysql/
    ports:
      - "3306:3306"
    init: true
    restart: on-failure
    secrets:
      - wp_db_pass
      - db_root_pass
      
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    networks:
      - inception
    env_file:
      - .env
    environment:
      WP_DB_PASS: /run/secrets/wp_db_pass
      WP_USER_PASS: /run/secrets/wp_user_pass
      WP_ADMIN_PASS: /run/secrets/wp_admin_pass
    volumes:
      - wordpress-data:/var/www/html/
    ports:
      - "9000:9000"
    init: true
    restart: on-failure
    depends_on:
      - mariadb
    secrets:
      - wp_db_pass
      - wp_user_pass
      - wp_admin_pass

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress-data
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_root_pass:
    file: ../secrets/DB_ROOT_PASS.txt
  wp_db_pass:
    file: ../secrets/WP_DB_PASS.txt
  wp_admin_pass:
    file: ../secrets/WP_ADMIN_PASS.txt
  wp_user_pass:
    file: ../secrets/WP_USER_PASS.txt
